name: uber
version: git
summary: Uber command line tool
description: |
  Get time to pickup estimates:-
    $ uber time 'pickup address here'

  Get price estimates:-
    $ uber price -s 'start address' -e 'end address'

grade: devel
confinement: strict

apps:
    uber:
        command: uber
parts:
  uber:
    plugin: nodejs
    source: https://github.com/jaebradley/uber-cli.git

